#!/bin/csh
#SBATCH -N 32
#SBATCH -t 24:00:00
#SBATCH -p pbatch

# Run info and srun job launch
srun -n 32 ./../../../../build-quartz-gcc@8.1.0-release/bin/geosx --input hi24l_co2_wells.xml  
echo 'Done'
